// Package crypto handles the two secrets-at-rest problems this proxy has:
// encrypting OAuth client secrets, certificate private keys and TOTP seeds
// stored in the database, and hashing the passwords that LAN services and
// admin users authenticate with.
package crypto

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"strings"
)

// Errors callers are expected to branch on.
var (
	ErrNoKeys        = errors.New("crypto: no encryption keys configured")
	ErrUnknownKey    = errors.New("crypto: ciphertext was sealed with a key that is not configured")
	ErrMalformed     = errors.New("crypto: malformed ciphertext")
	ErrDecryptFailed = errors.New("crypto: decryption failed")
)

const (
	// sealedVersion prefixes every stored value so the format can change later
	// without guessing at what old rows contain.
	sealedVersion = "v1"
	// keyLen is the AES-256 key size.
	keyLen = 32
	// maxKeyIDLen keeps key IDs short enough to stay readable in the DB.
	maxKeyIDLen = 32
)

// b64 is the encoding used for keys and sealed values: URL-safe and unpadded,
// so a sealed value is safe in a config file, a header or a URL.
var b64 = base64.RawURLEncoding

// Keyring decrypts with any configured key and encrypts with exactly one, so a
// key can be rotated by promoting a new primary while old rows stay readable.
type Keyring struct {
	primaryID string
	keys      map[string]cipher.AEAD
}

// NewKeyring builds a keyring from key specifications of the form
// "<id>:<base64url-encoded 32 bytes>". The first entry becomes the primary key
// used for new ciphertexts; the rest are accepted for decryption only.
//
// IDs exist so a ciphertext records which key sealed it. They are not secret.
func NewKeyring(specs ...string) (*Keyring, error) {
	if len(specs) == 0 {
		return nil, ErrNoKeys
	}

	kr := &Keyring{keys: make(map[string]cipher.AEAD, len(specs))}
	for i, spec := range specs {
		id, aead, err := parseKeySpec(spec)
		if err != nil {
			return nil, fmt.Errorf("key %d: %w", i, err)
		}
		if _, dup := kr.keys[id]; dup {
			return nil, fmt.Errorf("crypto: duplicate key id %q", id)
		}
		kr.keys[id] = aead
		if i == 0 {
			kr.primaryID = id
		}
	}
	return kr, nil
}

func parseKeySpec(spec string) (string, cipher.AEAD, error) {
	id, encoded, ok := strings.Cut(spec, ":")
	if !ok {
		return "", nil, errors.New("expected <id>:<base64-key>")
	}
	if id == "" || len(id) > maxKeyIDLen {
		return "", nil, fmt.Errorf("key id must be 1-%d characters", maxKeyIDLen)
	}
	if strings.ContainsAny(id, ".:") {
		// '.' separates the fields of a sealed value and ':' separates the spec.
		return "", nil, errors.New("key id must not contain '.' or ':'")
	}

	key, err := decodeKey(encoded)
	if err != nil {
		return "", nil, err
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		return "", nil, fmt.Errorf("aes: %w", err)
	}
	aead, err := cipher.NewGCM(block)
	if err != nil {
		return "", nil, fmt.Errorf("gcm: %w", err)
	}
	return id, aead, nil
}

// decodeKey accepts both unpadded and padded base64 so that a key generated by
// `openssl rand -base64 32` works without the operator having to strip '='.
func decodeKey(encoded string) ([]byte, error) {
	trimmed := strings.TrimRight(encoded, "=")
	key, err := b64.DecodeString(trimmed)
	if err != nil {
		// Fall back to the standard alphabet: `openssl rand -base64` emits
		// '+' and '/', which the URL-safe alphabet rejects.
		key, err = base64.RawStdEncoding.DecodeString(trimmed)
		if err != nil {
			return nil, errors.New("key is not valid base64")
		}
	}
	if len(key) != keyLen {
		return nil, fmt.Errorf("key must decode to %d bytes, got %d", keyLen, len(key))
	}
	return key, nil
}

// PrimaryKeyID reports which key new ciphertexts are sealed with.
func (k *Keyring) PrimaryKeyID() string { return k.primaryID }

// Encrypt seals plaintext with the primary key and returns a string safe to
// store in a text column.
//
// context is authenticated but not encrypted: it binds the ciphertext to the
// place it belongs, so a row's encrypted secret cannot be copied into a
// different row (or a different column) and still decrypt. Use a stable value
// such as "oauth_credentials/client_secret/<uuid>".
func (k *Keyring) Encrypt(plaintext []byte, context string) (string, error) {
	aead, ok := k.keys[k.primaryID]
	if !ok {
		return "", ErrNoKeys
	}

	nonce := make([]byte, aead.NonceSize())
	if _, err := rand.Read(nonce); err != nil {
		return "", fmt.Errorf("crypto: read random nonce: %w", err)
	}

	sealed := aead.Seal(nonce, nonce, plaintext, []byte(context))
	return sealedVersion + "." + k.primaryID + "." + b64.EncodeToString(sealed), nil
}

// EncryptString is Encrypt for values that are already text.
func (k *Keyring) EncryptString(plaintext, context string) (string, error) {
	return k.Encrypt([]byte(plaintext), context)
}

// Decrypt opens a value produced by Encrypt. context must match exactly what
// was passed to Encrypt.
func (k *Keyring) Decrypt(sealed, context string) ([]byte, error) {
	version, rest, ok := strings.Cut(sealed, ".")
	if !ok || version != sealedVersion {
		return nil, fmt.Errorf("%w: unrecognized format", ErrMalformed)
	}
	keyID, payload, ok := strings.Cut(rest, ".")
	if !ok || keyID == "" || payload == "" {
		return nil, fmt.Errorf("%w: missing key id or payload", ErrMalformed)
	}

	aead, ok := k.keys[keyID]
	if !ok {
		return nil, fmt.Errorf("%w: %q", ErrUnknownKey, keyID)
	}

	// Strict() rejects a final character whose unused bits are non-zero. Without
	// it those bits are silently discarded, so an attacker could alter the last
	// character of a stored value and still have it decode — a malleability the
	// AEAD below would never see.
	raw, err := b64.Strict().DecodeString(payload)
	if err != nil {
		return nil, fmt.Errorf("%w: payload is not valid base64", ErrMalformed)
	}
	if len(raw) < aead.NonceSize() {
		return nil, fmt.Errorf("%w: payload shorter than nonce", ErrMalformed)
	}

	nonce, ciphertext := raw[:aead.NonceSize()], raw[aead.NonceSize():]
	plaintext, err := aead.Open(nil, nonce, ciphertext, []byte(context))
	if err != nil {
		// Deliberately opaque: distinguishing "wrong key" from "tampered" or
		// "wrong context" would tell an attacker which knob to turn.
		return nil, ErrDecryptFailed
	}
	return plaintext, nil
}

// DecryptString is Decrypt for values that are text.
func (k *Keyring) DecryptString(sealed, context string) (string, error) {
	b, err := k.Decrypt(sealed, context)
	if err != nil {
		return "", err
	}
	return string(b), nil
}

// KeyIDOf reports which key sealed a value, without needing that key. It lets
// a rotation job find the rows that still use an old key.
func KeyIDOf(sealed string) (string, error) {
	version, rest, ok := strings.Cut(sealed, ".")
	if !ok || version != sealedVersion {
		return "", fmt.Errorf("%w: unrecognized format", ErrMalformed)
	}
	keyID, payload, ok := strings.Cut(rest, ".")
	if !ok || keyID == "" || payload == "" {
		return "", fmt.Errorf("%w: missing key id or payload", ErrMalformed)
	}
	return keyID, nil
}

// NeedsRotation reports whether a stored value was sealed with a key other than
// the current primary.
func (k *Keyring) NeedsRotation(sealed string) bool {
	id, err := KeyIDOf(sealed)
	return err == nil && id != k.primaryID
}

// GenerateKey returns a fresh key specification suitable for a config file or
// a Kubernetes Secret, e.g. "k1:8Jt...". Used by `smtp-auth-proxy genkey`.
func GenerateKey(id string) (string, error) {
	if id == "" || len(id) > maxKeyIDLen || strings.ContainsAny(id, ".:") {
		return "", fmt.Errorf("crypto: invalid key id %q", id)
	}
	key := make([]byte, keyLen)
	if _, err := rand.Read(key); err != nil {
		return "", fmt.Errorf("crypto: read random key: %w", err)
	}
	return id + ":" + b64.EncodeToString(key), nil
}
