-- Initial schema.
--
-- Identifiers are UUIDv7 strings so they sort by creation time and can be
-- generated by the application without a round trip.
--
-- managed_by records where an object came from: 'ui' for anything an operator
-- created, 'bootstrap' for objects declared in a bootstrap file. In reconcile
-- mode the admin UI refuses to edit 'bootstrap' rows, so the file stays the
-- source of truth.

CREATE TABLE oauth_credentials (
	id                     TEXT      NOT NULL PRIMARY KEY,
	name                   TEXT      NOT NULL,
	tenant_id              TEXT      NOT NULL,
	client_id              TEXT      NOT NULL,
	auth_type              TEXT      NOT NULL CHECK (auth_type IN ('secret', 'certificate')),
	-- Sealed with the encryption keyring; never readable from the API.
	client_secret_enc      TEXT      NOT NULL DEFAULT '',
	certificate_pem        TEXT      NOT NULL DEFAULT '',
	certificate_key_enc    TEXT      NOT NULL DEFAULT '',
	certificate_thumbprint TEXT      NOT NULL DEFAULT '',
	authority_host         TEXT      NOT NULL DEFAULT 'https://login.microsoftonline.com',
	-- When the secret or certificate expires, so the UI can warn ahead of time.
	expires_at             TIMESTAMPTZ,
	managed_by             TEXT      NOT NULL DEFAULT 'ui' CHECK (managed_by IN ('ui', 'bootstrap')),
	created_at             TIMESTAMPTZ NOT NULL,
	updated_at             TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX idx_oauth_credentials_name ON oauth_credentials (name);

CREATE TABLE mailboxes (
	id                  TEXT      NOT NULL PRIMARY KEY,
	-- The shared mailbox address. This is the value placed in the XOAUTH2
	-- "user=" field, which is what lets one app registration send as several
	-- different shared mailboxes.
	address             TEXT      NOT NULL,
	display_name        TEXT      NOT NULL DEFAULT '',
	oauth_credential_id TEXT      NOT NULL REFERENCES oauth_credentials (id) ON DELETE RESTRICT,
	transport           TEXT      NOT NULL DEFAULT 'smtp' CHECK (transport IN ('smtp', 'graph')),
	-- NULL means "use the global default". Exchange Online allows 30
	-- messages/minute and 3 concurrent connections per mailbox.
	rate_limit_per_min  INTEGER,
	max_concurrent      INTEGER,
	enabled             BOOLEAN   NOT NULL DEFAULT TRUE,
	managed_by          TEXT      NOT NULL DEFAULT 'ui' CHECK (managed_by IN ('ui', 'bootstrap')),
	created_at          TIMESTAMPTZ NOT NULL,
	updated_at          TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX idx_mailboxes_address ON mailboxes (address);
CREATE INDEX idx_mailboxes_credential ON mailboxes (oauth_credential_id);

CREATE TABLE smtp_accounts (
	id                 TEXT      NOT NULL PRIMARY KEY,
	username           TEXT      NOT NULL,
	password_hash      TEXT      NOT NULL,
	description        TEXT      NOT NULL DEFAULT '',
	-- Used when the From header matches no mailbox this account may send as.
	default_mailbox_id TEXT      REFERENCES mailboxes (id) ON DELETE SET NULL,
	from_policy        TEXT      NOT NULL DEFAULT 'reject'
		CHECK (from_policy IN ('reject', 'rewrite', 'passthrough')),
	-- JSON array of CIDRs. Empty means any source address is accepted.
	allow_cidrs        TEXT      NOT NULL DEFAULT '[]',
	rate_limit_per_min INTEGER,
	enabled            BOOLEAN   NOT NULL DEFAULT TRUE,
	last_used_at       TIMESTAMPTZ,
	managed_by         TEXT      NOT NULL DEFAULT 'ui' CHECK (managed_by IN ('ui', 'bootstrap')),
	created_at         TIMESTAMPTZ NOT NULL,
	updated_at         TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX idx_smtp_accounts_username ON smtp_accounts (username);

-- An account may be allowed to send as several mailboxes; the mailbox is then
-- chosen by matching the From header.
CREATE TABLE smtp_account_mailboxes (
	smtp_account_id TEXT NOT NULL REFERENCES smtp_accounts (id) ON DELETE CASCADE,
	mailbox_id      TEXT NOT NULL REFERENCES mailboxes (id) ON DELETE CASCADE,
	PRIMARY KEY (smtp_account_id, mailbox_id)
);

CREATE INDEX idx_account_mailboxes_mailbox ON smtp_account_mailboxes (mailbox_id);

-- Addresses an account may put in From beyond its own mailboxes. Patterns are
-- either an exact address or *@domain.
CREATE TABLE allowed_senders (
	id              TEXT      NOT NULL PRIMARY KEY,
	smtp_account_id TEXT      NOT NULL REFERENCES smtp_accounts (id) ON DELETE CASCADE,
	pattern         TEXT      NOT NULL,
	created_at      TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX idx_allowed_senders_unique ON allowed_senders (smtp_account_id, pattern);

CREATE TABLE messages (
	id                   TEXT      NOT NULL PRIMARY KEY,
	-- Accounts and mailboxes can be deleted while their history is retained,
	-- so these are nullable rather than cascading.
	smtp_account_id      TEXT      REFERENCES smtp_accounts (id) ON DELETE SET NULL,
	mailbox_id           TEXT      REFERENCES mailboxes (id) ON DELETE SET NULL,
	account_username     TEXT      NOT NULL DEFAULT '',
	mailbox_address      TEXT      NOT NULL DEFAULT '',
	envelope_from        TEXT      NOT NULL,
	header_from          TEXT      NOT NULL DEFAULT '',
	-- JSON array of recipient addresses.
	recipients           TEXT      NOT NULL,
	recipient_count      INTEGER   NOT NULL DEFAULT 0,
	size_bytes           INTEGER   NOT NULL DEFAULT 0,
	-- Only populated when log.include_subjects is enabled.
	subject              TEXT      NOT NULL DEFAULT '',
	message_id           TEXT      NOT NULL DEFAULT '',
	status               TEXT      NOT NULL DEFAULT 'queued'
		CHECK (status IN ('queued', 'sending', 'sent', 'deferred', 'failed', 'held')),
	attempts             INTEGER   NOT NULL DEFAULT 0,
	next_attempt_at      TIMESTAMPTZ NOT NULL,
	-- Lease-based claiming lets several replicas share one queue: a worker owns
	-- a message only until lease_expires_at, after which it can be reclaimed.
	lease_owner          TEXT,
	lease_expires_at     TIMESTAMPTZ,
	last_error           TEXT      NOT NULL DEFAULT '',
	last_error_code      TEXT      NOT NULL DEFAULT '',
	last_error_permanent BOOLEAN   NOT NULL DEFAULT FALSE,
	client_ip            TEXT      NOT NULL DEFAULT '',
	-- Set when storage.blob is fs; otherwise the body lives in message_blobs.
	blob_ref             TEXT      NOT NULL DEFAULT '',
	received_at          TIMESTAMPTZ NOT NULL,
	sent_at              TIMESTAMPTZ,
	updated_at           TIMESTAMPTZ NOT NULL
);

-- The queue poll: pending work, oldest due first.
CREATE INDEX idx_messages_claimable ON messages (status, next_attempt_at);
CREATE INDEX idx_messages_lease ON messages (lease_expires_at) WHERE lease_owner IS NOT NULL;
CREATE INDEX idx_messages_mailbox ON messages (mailbox_id, status);
CREATE INDEX idx_messages_account ON messages (smtp_account_id, received_at);
CREATE INDEX idx_messages_received ON messages (received_at);

CREATE TABLE message_blobs (
	message_id TEXT NOT NULL PRIMARY KEY REFERENCES messages (id) ON DELETE CASCADE,
	content    BYTEA NOT NULL
);

CREATE TABLE admin_users (
	id            TEXT      NOT NULL PRIMARY KEY,
	username      TEXT      NOT NULL,
	email         TEXT      NOT NULL DEFAULT '',
	display_name  TEXT      NOT NULL DEFAULT '',
	-- NULL for users that only sign in through the identity provider.
	password_hash TEXT,
	role          TEXT      NOT NULL CHECK (role IN ('admin', 'operator', 'viewer')),
	source        TEXT      NOT NULL DEFAULT 'local' CHECK (source IN ('local', 'oidc')),
	-- The identity provider's stable subject claim.
	subject       TEXT,
	totp_secret_enc TEXT    NOT NULL DEFAULT '',
	totp_enrolled_at TIMESTAMPTZ,
	disabled      BOOLEAN   NOT NULL DEFAULT FALSE,
	failed_logins INTEGER   NOT NULL DEFAULT 0,
	locked_until  TIMESTAMPTZ,
	last_login_at TIMESTAMPTZ,
	created_at    TIMESTAMPTZ NOT NULL,
	updated_at    TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX idx_admin_users_username ON admin_users (username);
CREATE UNIQUE INDEX idx_admin_users_subject ON admin_users (source, subject) WHERE subject IS NOT NULL;

CREATE TABLE admin_sessions (
	id           TEXT      NOT NULL PRIMARY KEY,
	user_id      TEXT      NOT NULL REFERENCES admin_users (id) ON DELETE CASCADE,
	-- Only the hash is stored: a stolen database must not yield usable sessions.
	token_hash   TEXT      NOT NULL,
	csrf_token   TEXT      NOT NULL,
	ip           TEXT      NOT NULL DEFAULT '',
	user_agent   TEXT      NOT NULL DEFAULT '',
	created_at   TIMESTAMPTZ NOT NULL,
	last_seen_at TIMESTAMPTZ NOT NULL,
	expires_at   TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX idx_admin_sessions_token ON admin_sessions (token_hash);
CREATE INDEX idx_admin_sessions_user ON admin_sessions (user_id);
CREATE INDEX idx_admin_sessions_expiry ON admin_sessions (expires_at);

CREATE TABLE audit_logs (
	id          TEXT      NOT NULL PRIMARY KEY,
	at          TIMESTAMPTZ NOT NULL,
	actor_type  TEXT      NOT NULL CHECK (actor_type IN ('user', 'system', 'bootstrap')),
	actor_id    TEXT      NOT NULL DEFAULT '',
	actor_name  TEXT      NOT NULL DEFAULT '',
	action      TEXT      NOT NULL,
	target_type TEXT      NOT NULL DEFAULT '',
	target_id   TEXT      NOT NULL DEFAULT '',
	target_name TEXT      NOT NULL DEFAULT '',
	-- JSON diff of what changed, with secret values masked before it is written.
	details     TEXT      NOT NULL DEFAULT '{}',
	result      TEXT      NOT NULL DEFAULT 'success' CHECK (result IN ('success', 'failure')),
	ip          TEXT      NOT NULL DEFAULT '',
	user_agent  TEXT      NOT NULL DEFAULT ''
);

CREATE INDEX idx_audit_logs_at ON audit_logs (at);
CREATE INDEX idx_audit_logs_actor ON audit_logs (actor_id, at);
CREATE INDEX idx_audit_logs_target ON audit_logs (target_type, target_id, at);
